name: BattlyCapePlugin
version: 1.0.3
main: racsu.planet.BattlyCapePlugin
api-version: 1.21
commands:
  capabattly:
    description: Verifica la membresía de Battly Launcher y genera un código promocional.
    usage: /<command>
    permission: battlycape.use
permissions:
  battlycape.use:
    description: Permite usar el comando para generar códigos promocionales de Battly Launcher.
    default: true
  battlycape.bypass:
    description: Permite generar múltiples códigos sin límite.
    default: op